### ISSUE TITLE
按照文档的开始使用，yarn build 时报错了

### ISSUE THREAD

**Issue by nolanlee** [vueblocks/ve-charts#100]
如题
```
 ERROR  Failed to compile with 1 errors                                                                                       4:39:31 PM

 error  in ./node_modules/ve-charts/lib/ve-charts.min.css

Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: Loading PostCSS Plugin failed: Cannot find module 'postcss-import'

(@/vue-demo/node_modules/ve-charts/.postcssrc.js)
    at load (/vue-demo/node_modules/postcss-load-config/src/plugins.js:21:13)
    at Object.keys.filter.map (/vue-demo/node_modules/postcss-load-config/src/plugins.js:53:16)
    at Array.map (<anonymous>)
    at plugins (/vue-demo/node_modules/postcss-load-config/src/plugins.js:52:8)
    at config.load.then (/vue-demo/node_modules/postcss-load-config/src/index.js:72:18)

 @ ./node_modules/ve-charts/lib/ve-charts.min.css 4:14-142 14:3-18:5 15:22-150
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://172.30.26.4:8082/sockjs-node (webpack)/hot/dev-server.js ./src/main.js
```

dependences:
```json
{
  "echarts": "^4.3.0",
  "express": "^4.16.4",
  "ve-charts": "^0.8.3",
  "vue": "^2.5.22"
}
```

code:
```javascript
import Vue from 'vue'
import App from './App.vue'
import VeCharts from 've-charts'
import 've-charts/lib/ve-charts.min.css'

Vue.config.productionTip = false
Vue.use(VeCharts)

new Vue({
  render: h => h(App),
}).$mount('#app')
```

**Comment by xiaoluoboding** [comment]
@nolanlee 您好，看报错，有没有尝试安装这个包试下：

`npm i postcss-import -D`

**Comment by nolanlee** [comment]
> @nolanlee 您好，看报错，有没有尝试安装这个包试下：
> 
> `npm i postcss-import -D`

需要安装 `postcss-import` 和 `postcss-url`，因为 package 里有 `.postcssrc.js`

**Comment by nolanlee** [comment]
建议重新打包一下，`import 've-charts/lib/ve-charts.min.css'` 不需要 postcss

**Comment by xiaoluoboding** [comment]
@nolanlee OK. 谢谢反馈
